---
services:
  overlay:
    image: nginx:latest
    container_name: overlay
    ports:
      - 8080:80
    volumes:
      - ./oskar:/usr/share/nginx/html/oskar
      - ./gilbert:/usr/share/nginx/html/gilbert
